name: actions_workflow

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@main
      - name: simple_js_action
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: Davis
      - name: log_greet_time
        run: echo "${{ steps.greet.outputs.time }}"
      - name: list_files
        uses: |
          pwd
          ls- la
 