name: actions_workflow

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          path: main
      - name: simple_js_action
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: Davis
      - name: list_files
        needs: ["checkout"]
        run: |
          pwd
          ls- la