name: actions_workflow

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: simple_js_action
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: Davis
      - nane: log_greet_time
        run: echo "${{ steps.greet.outputs.time }}"

